config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users

  resources :users, only: [] do
    resources :images, only: [:index]
  end

  resources :images, except: [:index]

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, FileUploader

  belongs_to :user

  validates :name, :file, presence: true

  def self.reprocess_images
    Image.find_each do |image|
      if image.file?
        image.file.recreate_versions!
        image.save!
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    user_images_path(resource.id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :check_access, only: [:edit, :update, :destroy]



  # GET /images
  # GET /images.json
  def index
    @images = Image.where(user_id: params[:user_id].to_i)
    @it_is_my_images_list = current_user && (current_user.id == params[:user_id].to_i)
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to user_images_path(current_user), notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_access
    unless @image.user == current_user
      flash[:warning] = "You can edit only your own images!"
      redirect_to user_images_path(current_user)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      hash = params.fetch(:image, {}).permit(:name, :file, :file_cache)
      hash['user_id'] = current_user.id
      hash
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.slim
= simple_form_for(@image) do |f|
  = f.error_notification

  = f.input :name
  = f.input :file, as: :file
  = f.hidden_field :file_cache

  .form-actions
    = f.button :submit

app/views/images/edit.html.slim
- content_for :header do
  | Editing image

= render 'form'

app/views/images/index.html.slim
- content_for :header do
  = @it_is_my_images_list ? 'My Collection' : 'Collection'

  - if @it_is_my_images_list
    = link_to new_image_path, class: 'btn btn-primary btn-header' do
      span.glyphicon.glyphicon-plus
      |  New Image

.mt-10
  'Share link:
  span.share-link = link_to user_images_url(params[:user_id])

- if @images.any?
  .table-responsive.mt-50
    table.table.table-striped.table-hover
      thead
        tr
          th Name
          th colspan="4"
      tbody
        - @images.each do | image |
          tr
            td = image.name
            td = image_tag image.file.thumb.url, id: "image-#{image.id}"
            td
              = link_to 'Show', image
            td
              - if @it_is_my_images_list
                = link_to 'Edit', edit_image_path(image)
            td
              - if @it_is_my_images_list
                = link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete-#{image.id}"
- else
  h4 There are no images

app/views/images/new.html.slim
- content_for :header do
  |Upload Image

= render 'form'

app/views/images/show.html.slim
- content_for :header do
  | Show image

  - if current_user && (current_user.id == @image[:user_id].to_i)
      = link_to edit_image_path(@image), class: 'btn btn-primary btn-header' do
        span.glyphicon.glyphicon-pencil
        |  Edit

h4
  em = @image.name

.clearfix = image_tag @image.file.url, class: 'image-big', id: "image-#{@image.id}"

.mt-10
  'Share link:
  span.share-link = link_to image_url(@image)

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Media"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to 'Media', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li = link_to "All Collections", root_path
          - if current_user
            ul.nav.navbar-nav
              li= link_to "My Collection", user_images_path(current_user.id)
            ul.nav.navbar-nav.nav-right
              li= link_to "Sign out", destroy_user_session_path, :method => :delete, id: 'sign-out-link', class: 'logout_link'
          - else
            ul.nav.navbar-nav.nav-right
              li = link_to "Log in", new_user_session_path, id: 'log-in-link'
              li = link_to "Sign up", new_user_registration_path, id: 'sign-up-link'


    .container
      .row
        .col-lg-12
          #bootstrap_flashes
            = bootstrap_flash
          - if content_for?(:header)
            .page-header
              h1 = yield :header
          = yield


      footer
        p &copy; Media 2016

app/views/welcome/index.slim
- content_for :header do
  |Welcome

h3 Here you can see all collections!

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th User
        th colspan="2"
    tbody
      - @users.each do |user|
        tr
          td = user.email
          td = link_to 'Show Collection', user_images_path(user.id)